name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
  
    

      
    - name: Install dependencies
      run: make build
    with:
    -name: grepper-py binary
     path: /home/runner/work/grepper_py/grepper_py/dist/main
      

